### ISSUE TITLE
Where are non-test files

### ISSUE THREAD

**Issue by stephenharper82** [JoyOfJavaScript/joj#7]
Have read and re-read instructions to make sure I've not done anything wrong. I can only see .spec files , e.g. 

![image](https://user-images.githubusercontent.com/10153802/79256831-95a8c200-7e80-11ea-8cd0-9fdbe444b6f3.png)

Any idea where I'm going wrong?

Thanks

**Comment by stephenharper82** [comment]
OK, so I now understand that the test is having the code we want to look at - apologies. 
I'm getting "Error: Not supported on first import statement. I have upgraded to node 12. I'm using WSL. TBH, wondering if I'm maybe biting off more than I can chew with this book since I'm a bit of a javascript novice.

**Comment by luijar** [comment]
Yeah, the chapter-listings repo only has .spec as they are all unit tests. All of the snippets in the book are captured as unit tests. To run, you should only need to install Docker Desktop (Mac, Windows, Linux, etc) and then run docker-compose up. Let me know if you're still having trouble with this, I'd be happy to help troubleshoot.

Also, if any of the concepts are hard to grasp, let me know and I'll be happy to help. Perhaps it's on my part if something is not explained well. Feel free to drop me a tweet @luijar

**Comment by stephenharper82** [comment]
I tried to install docker desktop, but I'm running Windows 10 Home edition so I'm unable to install per: https://forums.docker.com/t/installing-docker-on-windows-10-home/11722/21. 
So I installed DockerToolbox.... After installing I launched it, then navigated to the project directory and did docker-compose up, but I seem to be getting the same issue:

5822c4107e4: Extracting [==================================================>]  75822c4107e4: Pull complete                                                     ac44bd3f6020: Extracting [==================================================>]  ac44bd3f6020: Extracting [==================================================>]  ac44bd3f6020: Pull complete                                                     Digest: sha256:cce9ed2b82c33e8b339c3f744bef72a93ef8862a8615aeb364cdafdf326b552a
Status: Downloaded newer image for node:13.2.0-slim
Creating joj_chapter_listings_1 ... done                                        Creating joj_blockchain_tests_1 ... done                                        Attaching to joj_blockchain_tests_1, joj_chapter_listings_1
chapter_listings_1  |
chapter_listings_1  | > @joj/blockchain@1.0.0 build /home/joj/src/blockchain
chapter_listings_1  | > rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: not found
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! syscall spawn
chapter_listings_1  | npm ERR! file sh
chapter_listings_1  | npm ERR! errno ENOENT
chapter_listings_1  | npm ERR! @joj/blockchain@1.0.0 build: `rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist`
chapter_listings_1  | npm ERR! spawn ENOENT
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/blockchain@1.0.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-15T18_04_47_240Z-debug.log
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 test-all /home/joj/src/chapter-listings
chapter_listings_1  | > rm -rf _babel && npm run build; mocha "_babel/**/*spec.mjs"; rm -rf _babel
chapter_listings_1  |
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 build /home/joj/src/chapter-listings
chapter_listings_1  | > babel src --out-dir _babel/src --keep-file-extension --copy-files
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: Protocol error
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! errno 2
chapter_listings_1  | npm ERR! @joj/chapter-listings@0.1.0 build: `babel src --out-dir _babel/src --keep-file-extension --copy-files`
chapter_listings_1  | npm ERR! Exit status 2
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/chapter-listings@0.1.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-15T18_05_09_776Z-debug.log
chapter_listings_1  | sh: 1: mocha: Protocol error
joj_chapter_listings_1 exited with code 0
blockchain_tests_1  |
blockchain_tests_1  | > @joj/blockchain@1.0.0 test-all /home/joj/src/blockchain
blockchain_tests_1  | > rm -rf _babel && babel src --out-dir _babel/src --keep-file-extension && babel test --out-dir _babel/test --keep-file-extension; mocha "_babel/**/*spec.js" --exit; rm -rf _babel
blockchain_tests_1  |
blockchain_tests_1  | sh: 1: babel: not found
blockchain_tests_1  | sh: 1: mocha: not found
joj_blockchain_tests_1 exited with code 0

steph@HARPATRON15 MINGW64 ~/dev/js/joj (master)
$

**Comment by stephenharper82** [comment]
Should have said - thanks for getting back to me so quickly! Much appreciated.

**Comment by stephenharper82** [comment]
trying to run npm install on windows

C:\Users\steph\dev\js\joj\src\chapter-listings>npm install
npm ERR! code UNKNOWN
npm ERR! syscall open
npm ERR! path C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\@joj\blockchain\npm-shrinkwrap.json
npm ERR! errno -4094
npm ERR! UNKNOWN: unknown error, open 'C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\@joj\blockchain\npm-shrinkwrap.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steph\AppData\Roaming\npm-cache\_logs\2020-04-15T20_32_28_561Z-debug.log

C:\Users\steph\dev\js\joj\src\chapter-listings>npm -v
6.13.4

C:\Users\steph\dev\js\joj\src\chapter-listings>node -v
v12.16.1

**Comment by luijar** [comment]
That's strange I don't see the call nom install within the container. Let me check.

**Comment by luijar** [comment]
Made a small change and checked it in. It might work. Please pull the latest and retry. Let me know.

**Comment by stephenharper82** [comment]
Thanks, but I'm still having issues:

$ docker-compose up                                                                                                                                                                                                                         WARNING: Some networks were defined but are not used by any service: tjoj-network
Recreating joj_chapter_listings_1 ... done                                                                                                                                                                                                  Starting joj_blockchain_tests_1   ... done                                                                                                                                                                                                  Attaching to joj_blockchain_tests_1, joj_chapter_listings_1
chapter_listings_1  | npm ERR! cb() never called!
chapter_listings_1  |
chapter_listings_1  | npm ERR! This is an error with npm itself. Please report this error at:
chapter_listings_1  | npm ERR!     <https://npm.community>
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-16T16_52_47_724Z-debug.log
chapter_listings_1  |
chapter_listings_1  | > @joj/blockchain@1.0.0 build /home/joj/src/blockchain
chapter_listings_1  | > rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: not found
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! syscall spawn
chapter_listings_1  | npm ERR! file sh
chapter_listings_1  | npm ERR! errno ENOENT
chapter_listings_1  | npm ERR! @joj/blockchain@1.0.0 build: `rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist`
chapter_listings_1  | npm ERR! spawn ENOENT
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/blockchain@1.0.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
blockchain_tests_1  | sh: 1: link-module-alias: not found
blockchain_tests_1  |
blockchain_tests_1  | > @joj/blockchain@1.0.0 test-all /home/joj/src/blockchain
blockchain_tests_1  | > rm -rf _babel && babel src --out-dir _babel/src --keep-file-extension && babel test --out-dir _babel/test --keep-file-extension; mocha "_babel/**/*spec.js" --exit; rm -rf _babel
blockchain_tests_1  |
blockchain_tests_1  | sh: 1: babel: not found
blockchain_tests_1  | sh: 1: mocha: not found
joj_blockchain_tests_1 exited with code 0
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-16T16_52_48_325Z-debug.log
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 test-all /home/joj/src/chapter-listings
chapter_listings_1  | > rm -rf _babel && npm run build; mocha "_babel/**/*spec.mjs"; rm -rf _babel
chapter_listings_1  |
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 build /home/joj/src/chapter-listings
chapter_listings_1  | > babel src --out-dir _babel/src --keep-file-extension --copy-files
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: Protocol error
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! errno 2
chapter_listings_1  | npm ERR! @joj/chapter-listings@0.1.0 build: `babel src --out-dir _babel/src --keep-file-extension --copy-files`
chapter_listings_1  | npm ERR! Exit status 2
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/chapter-listings@0.1.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-16T16_52_59_174Z-debug.log
chapter_listings_1  | sh: 1: mocha: Protocol error
joj_chapter_listings_1 exited with code 0

**Comment by luijar** [comment]
Strange. Working great on mine. I actually checked in all files I had. Some work in progress, but I rather unblock you. Please do a pull of the master branch, then let's your Docker images just in case. Do **docker system prune** and follow directions to clean all. Then try running **docker-compose** again. Let me know.

**Comment by stephenharper82** [comment]
Many thanks, but I'm still having same issue. Followed your steps as per below.  Seems to always complain about babel - am I better trying to install this globally? I wouldn't have thought this was required from docker though - surely the container would install it itself ( I have no experience of docker?)

Ensure up to date code:

harpatron@HARPATRON15:/mnt/c/Users/steph/dev/js/joj$ git reset --hard
HEAD is now at 6f36256 Checked in raw scratch pad files for CH8 and 9
harpatron@HARPATRON15:/mnt/c/Users/steph/dev/js/joj$ git pull
Already up to date.
harpatron@HARPATRON15:/mnt/c/Users/steph/dev/js/joj$ git branch
* master

docker commands as given:

harpatron@HARPATRON15:/mnt/c/Users/steph/dev/js/joj$
$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers:
948f2675c30308ea36974af7d47f96501dc717118c5a018cadb671227a938ec3
182f99c223e22185d0a87038fd8b4390a2b4b8afbed3f6eb1d3a0442530be531

Deleted Networks:
joj_default

Total reclaimed space: 22.93MB

steph@HARPATRON15 MINGW64 ~/dev/js/joj/src/chapter-listings (master)
$ docker-compose up
Creating network "joj_tjoj-network" with the default driver
Creating joj_chapter_listings_1 ... done                                                                                                                                                                        Creating joj_blockchain_tests_1 ... done                                                                                                                                                                        Attaching to joj_chapter_listings_1, joj_blockchain_tests_1
chapter_listings_1  |
chapter_listings_1  | > @joj/blockchain@1.0.0 postinstall /home/joj/src/blockchain
chapter_listings_1  | > link-module-alias
chapter_listings_1  |
chapter_listings_1  | sh: 1: link-module-alias: not found
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! syscall spawn
chapter_listings_1  | npm ERR! file sh
chapter_listings_1  | npm ERR! errno ENOENT
chapter_listings_1  | npm ERR! @joj/blockchain@1.0.0 postinstall: `link-module-alias`
chapter_listings_1  | npm ERR! spawn ENOENT
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/blockchain@1.0.0 postinstall script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
blockchain_tests_1  | sh: 1: link-module-alias: not found
blockchain_tests_1  |
blockchain_tests_1  | > @joj/blockchain@1.0.0 test-all /home/joj/src/blockchain
blockchain_tests_1  | > rm -rf _babel && babel src --out-dir _babel/src --keep-file-extension && babel test --out-dir _babel/test --keep-file-extension; mocha "_babel/**/*spec.js" --exit; rm -rf _babel
blockchain_tests_1  |
blockchain_tests_1  | sh: 1: babel: not found
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-17T18_12_27_568Z-debug.log
chapter_listings_1  |
chapter_listings_1  | > @joj/blockchain@1.0.0 build /home/joj/src/blockchain
chapter_listings_1  | > rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: not found
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! syscall spawn
chapter_listings_1  | npm ERR! file sh
chapter_listings_1  | npm ERR! errno ENOENT
chapter_listings_1  | npm ERR! @joj/blockchain@1.0.0 build: `rm -rf dist && babel src --out-dir dist --keep-file-extension && cp -f package.json dist`
chapter_listings_1  | npm ERR! spawn ENOENT
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/blockchain@1.0.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
blockchain_tests_1  | sh: 1: mocha: not found
joj_blockchain_tests_1 exited with code 0
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-17T18_12_28_317Z-debug.log
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 test-all /home/joj/src/chapter-listings
chapter_listings_1  | > rm -rf _babel && npm run build; mocha "_babel/**/*spec.mjs"; rm -rf _babel
chapter_listings_1  |
chapter_listings_1  |
chapter_listings_1  | > @joj/chapter-listings@0.1.0 build /home/joj/src/chapter-listings
chapter_listings_1  | > babel src --out-dir _babel/src --keep-file-extension --copy-files
chapter_listings_1  |
chapter_listings_1  | sh: 1: babel: Protocol error
chapter_listings_1  | npm ERR! code ELIFECYCLE
chapter_listings_1  | npm ERR! errno 2
chapter_listings_1  | npm ERR! @joj/chapter-listings@0.1.0 build: `babel src --out-dir _babel/src --keep-file-extension --copy-files`
chapter_listings_1  | npm ERR! Exit status 2
chapter_listings_1  | npm ERR!
chapter_listings_1  | npm ERR! Failed at the @joj/chapter-listings@0.1.0 build script.
chapter_listings_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
chapter_listings_1  |
chapter_listings_1  | npm ERR! A complete log of this run can be found in:
chapter_listings_1  | npm ERR!     /home/node/.npm/_logs/2020-04-17T18_12_40_924Z-debug.log
chapter_listings_1  | sh: 1: mocha: Protocol error
joj_chapter_listings_1 exited with code 0

steph@HARPATRON15 MINGW64 ~/dev/js/joj/src/chapter-listings (master)
$

**Comment by luijar** [comment]
You should not have to do anything. That's why I'm using Docker so that you don't have to install any tools or upgrade Node.js. It should all run there self-contained. I wonder what else it could be. I use a Mac, and don't have access to a Win10 system. The first thing I do is npm install. Try this: in docker-compose.yml you'll see 2 services: blockchain_tests and chapter_listings. Try removing chapter-listings completely. So, remove this entire block: 

chapter_listings:
      image: "node:13.2.0-slim"
      user: "node"
      working_dir: /home/joj/src
      environment:
        - NODE_ENV=dev
        - NPM_CONFIG_LOGLEVEL=error
      volumes:
        - ./src:/home/joj/src
      command: bash -c  "npm --prefix /home/joj/src/blockchain install; npm --prefix /home/joj/src/blockchain run build ; npm --prefix /home/joj/src/chapter-listings install --silent --progress=false ; npm --prefix /home/joj/src/chapter-listings run test-all"
      networks:
      - tjoj-network

**Comment by luijar** [comment]
docker-compose down and then docker-compose up

**Comment by luijar** [comment]
Hey, any luck? I pushed in more code today. Cleaning up CH8. Please try again. If not, I'm in the process of cleaning up CH09 code and checking that in. Then both of us we'll definitely have the same setup. Also, I'll try upgrading the Docker image to latest Node.js version

**Comment by stephenharper82** [comment]
hi - sorry. I didn't have a chance to look at this for a couple of weeks.  Still having the same issue. Have taken latest, docker system prune, docker-compose up and get exact same error. 

I'm now trying to do it from command line again. 


C:\Users\steph\dev\js\joj\src\chapter-listings>node -v
v12.16.1

C:\Users\steph\dev\js\joj\src\chapter-listings>npm -v
6.13.4

C:\Users\steph\dev\js\joj\src\chapter-listings>npm run test

> @joj/chapter-listings@0.1.0 test C:\Users\steph\dev\js\joj\src\chapter-listings
> mocha

Error: No test files found: "test"

Trying to change command to run 
 @joj/chapter-listings@0.1.0 test C:\Users\steph\dev\js\joj\src\chapter-listings
> mocha 'src/**/*.mjs'

Error: Not supported
    at Object.exports.requireOrImport (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\esm-utils.js:11:23)
    at Object.exports.loadFilesAsync (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\esm-utils.js:32:34)
    at Mocha.loadFilesAsync (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\mocha.js:342:19)
    at Mocha.runAsync (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\mocha.js:953:12)
    at Object.exports.singleRun (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\cli\run-helpers.js:109:16)
    at exports.runMocha (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\cli\run-helpers.js:151:20)
    at Object.exports.handler (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\cli\run.js:307:11)
    at Object.runCommand (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\node_modules\yargs\yargs.js:1087:28)
    at Object.parse (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> (C:\Users\steph\dev\js\joj\src\chapter-listings\node_modules\mocha\bin\mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

**Comment by stephenharper82** [comment]
> Also, I'll try upgrading the Docker image to latest Node.js version

How do I do this? I didn't think I specified this?

**Comment by stephenharper82** [comment]
Progress now after upgrading to latest node (14.1.0). I can't run from top level directory - need to navigate to a specific test and do 

harpatron@HARPATRON15:/mnt/c/Users/steph/dev/js/joj/src/chapter-listings/src/ch01$ mocha 1-3-2.spec.mjs


  1.3.2 - JavaScript objects: no fluff, just stuff
    ✓ Object literals
    ✓ Object constructor
    ✓ Classes
    ✓ Delegation
    ✓ Functional Mixins


  5 passing (10ms)


Progress!

**Comment by stephenharper82** [comment]
I believe it's to do with node compatibility with .mjs files
